### ISSUE TITLE
Dark Theme temporarily disappears when exiting presentation mode

### ISSUE THREAD

**Issue by LaurenzV** [typst/webapp-issues#463] opened 2024-10-15 09:07 UTC
### Description

Steps to reproduce:
1. Set the web app into dark mode.
2. Open a project.
3. Press the "Start presentation" button.
4. Press "Esc".
5. The web app is now in light mode. Once I refresh the web page, it goes back into dark mode, though.

### Browsers

Firefox

### OS

macOS

**Comment by laurmaedje** [comment] 2024-10-15 09:16
Duplicate of https://github.com/typst/webapp-issues/issues/433

**Closed as not planned by laurmaedje** 2024-10-15 09:16 UTC
Labels: bug, duplicate
