### ISSUE TITLE
#sym.square.stroked.big shows incorrectly in preview

### ISSUE THREAD

**Issue by wuhongyewhy** [typst/webapp-issues#252] opened 2024-01-02 02:41 UTC
### Description

stroked.big and stroked.tiny show a grey box without boards， but in the final pdf， they are stroked boxes without grey fill。

input file as follow:

`#sym.square` $->$ #sym.square

`#sym.square.stroked` $->$ #sym.square.stroked

`#sym.square.stroked.big` $->$ #sym.square.stroked.big

`#sym.square.stroked.tiny` $->$ #sym.square.stroked.tiny

![image](https://github.com/typst/webapp-issues/assets/7631427/269dce7e-6787-49a3-84d2-9ee21da84b16)
fig. 1. In preview

![image](https://github.com/typst/webapp-issues/assets/7631427/af832e6e-2380-4654-9b1a-146aec70bc88)
fig. 2. Final pdf

### Browsers

Chrome

### OS

Windows

**Comment by laurmaedje** [comment] 2024-01-02 08:35
This is because the preview is capable of rendering emoji while the PDF output isn't yet. Duplicate of https://github.com/typst/typst/issues/144.

**Closed by laurmaedje** 2024-01-02 08:35 UTC
Labels: bug
