### ISSUE TITLE
When pasting image, use random name like uuid instead of image.png

### ISSUE THREAD

**Issue by knarkzel** [typst/webapp-issues#189] opened 2023-11-02 19:57 UTC
### Description

When I want to paste multiple images, I have to rename each image manually because the pasted image is always namned `image.png`.

**Comment by laurmaedje** [comment] 2023-11-02 20:34
Duplicate of https://github.com/typst/webapp-issues/issues/168#issuecomment-1791458446

**Closed by laurmaedje** 2023-11-02 20:34 UTC
Labels: bug
