### ISSUE TITLE
Show rules mess with the go-to-definition functionality in the web app

### ISSUE THREAD

**Issue by LaurenzV** [typst/webapp-issues#446] opened 2024-10-01 14:36 UTC
### Description

See the reproduction URL. Try to click for example on `Etiam` in the second sentence, and it will correctly jump back to the corresponding location in the source code.

Now uncomment the show rule and try again, and it will jump to a slightly different location instead.

### Reproduction URL

https://typst.app/project/rkdshblstJ3CQV_ZSOdH3s

**Comment by laurmaedje** [comment] 2024-10-01 14:40
Duplicate of https://github.com/typst/typst/issues/2854

**Closed as not planned by laurmaedje** 2024-10-01 14:40 UTC
Labels: bug, duplicate

**Comment by laurmaedje** [comment] 2024-10-01 14:41
Fwiw, I usually call this "jump from click" or "to-source jump" to distinguish it from the "go to definition" for variables triggered via Ctrl+Click.

**Comment by LaurenzV** [comment] 2024-10-01 14:42
Ah oops, sorry for the duplicate.

**Comment by laurmaedje** [comment] 2024-10-01 14:43
No problem.
