### ISSUE TITLE
Comment only share-link

### ISSUE THREAD

**Issue by pohlm01** [typst/webapp-issues#465] opened 2024-10-17 15:45 UTC
### Description

It would be great to have a link to share that does not allow modifying the text, but only placing/answering comments. If the "tracing changes" feature becomes available, it might also be nice to allow editing but force the tracing of changes.

### Use Case

This is helpful to receive feedback while at the same time being sure that nothing can be changed without noticing.

**Comment by laurmaedje** [comment] 2024-10-17 16:01
Duplicate of https://github.com/typst/webapp-issues/issues/439

**Closed as not planned by laurmaedje** 2024-10-17 16:01 UTC
Labels: duplicate, feature request
