### ISSUE TITLE
Add file tree structure

### ISSUE THREAD

**Issue by christofergartner** [typst/webapp-issues#332] opened 2024-04-27 16:31 UTC
### Description

Allow creating directories for different projects to be groupable into a common folder with a chosen name.

### Use Case

Makes it far easier to organize different projects for different purposes.

**Comment by PgBiel** [comment] 2024-04-27 16:34
Duplicate of https://github.com/typst/webapp-issues/issues/62

**Closed** 2024-04-29 12:11 UTC
Labels: feature request
