### ISSUE TITLE
Ctrl+V unique image name

### ISSUE THREAD

**Issue by trustedtomato** [typst/webapp-issues#361] opened 2024-05-28 12:00 UTC
### Description

Right now, pasting an image makes an image.png and adds the appropriate code, which is super convenient. However, the feature would be even more useful, if doing this multiple times would cause the creation of image-1.png, image-2.png, etc. and the creation of the appropriate code. In other words, the pasting feature should look if image.png exists, and if so, use a suffix which does not exist yet.

### Use Case

Faster addition of multiple pasted images. (This way, I just have to paste multiple times. Right now, I have to paste, rename file, change code, and repeat. It would also be nice if renaming an image would automatically rename it in the code, but that's a different feature request.)
This would be super convenient, since presumably a lot of people use Typst to create things which they want to create quickly, like a homework, or a standardized looking presentation.

**Comment by laurmaedje** [comment] 2024-05-28 20:26
Duplicate of https://github.com/typst/webapp-issues/issues/168

**Closed by laurmaedje** 2024-05-28 20:26 UTC
Labels: feature request
