### ISSUE TITLE
Ability to rename an image and all references

### ISSUE THREAD

**Issue by Aevyz** [typst/webapp-issues#255] opened 2024-01-06 17:12 UTC
### Description

When I rename an image, e.g. image.png to image_2.png, it should search for all references of `#image("image.png")` and change it to `#image("image2.png")`

### Use Case

Quality of Life update so that renaming images is more convenient.

**Comment by laurmaedje** [comment] 2024-11-30 12:51
Duplicate of https://github.com/typst/webapp-issues/issues/81

**Closed by laurmaedje** 2024-11-30 12:51 UTC
Labels: feature request, editor
