### ISSUE TITLE
When web app makes suggestion with dropdown, compile preview with hovered selection

### ISSUE THREAD

**Issue by JamesxX** [typst/webapp-issues#402] opened 2024-07-18 11:05 UTC
### Description

When the web app suggests something with the dropdown, as shown in the picture below;

![image](https://github.com/user-attachments/assets/019b973b-9537-43b7-b7c8-82906b178ab5)

You can hover and/or change the selection with arrow keys, however, it would be more useful to compile and show the document as if the highlighted selection had been placed in the document

### Use Case

It would greatly improve the speed with which I can typset and I don't have names of every symbol in my head, but I probably do know what it looks like, so previewing the selection would make finding the correct one easier.

Other suggestions include a symbols tab on the left

**Comment by laurmaedje** [comment] 2024-07-18 11:12
Duplicate of https://github.com/typst/webapp-issues/issues/184

**Closed by laurmaedje** 2024-07-18 11:12 UTC
Labels: feature request
