### ISSUE TITLE
Import from GitHub used to work but does not now

### ISSUE THREAD

**Issue by principletest** [typst/webapp-issues#382] opened 2024-06-18 01:10 UTC
### Description

Last year when we published these: 

https://github.com/onefact/datathinking.org-report-template

https://github.com/onefact/letterhead-template/

Then the Typst webapp let us import a repository from @GitHub, similar to @overleaf or @google colaboratry (https://colab.google/) which lets you import Jupyter notebooks straight from GitHub :)

Right now this does not seem supported - is it on the roadmap?

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, macOS, Android, iOS or iPad OS

**Comment by oplik0** [comment] 2024-10-10 13:13
I think I might've found the reason why importing is broken now - it turns out importing repositories that contains a pdf file (on the branch you're importing) is what's broken.

Minimal example: https://github.com/oplik0/typst-test-import

Trying to import the `pdf` (should be default, but check the advanced settings) branch typically results in a "Cannon create project: the file is not an acceptable format" error. Sometimes trying to import a repo with a pdf just silently fails.

Importing the `clean` branch works just fine.

I see that the web app seems to convert uploaded PDFs to SVG, so I'd guess the issue is related to that.

**Comment by laurmaedje** [comment] 2024-10-10 13:43
> Last year when we published these:

> Then the Typst webapp let us import a repository

Are you talking about _importing_ something from GitHub (i.e. with `#import` keyword)? Because that was never supported.

What _is_ supported is connecting projects to Git repositories, so that you collaborate across the web app and a Git repository. But this is a fairly recent feature, which definitely did not exist last year.

> I think I might've found the reason why importing is broken now - it turns out importing repositories that contains a pdf file (on the branch you're importing) is what's broken.

Yes, this is unfortunate. Right now if there are forbidden files, the clone fails. We are working to fix this, so that instead they are just ignored for the purposes of Git sync.

**Comment by oplik0** [comment] 2024-10-10 15:32
> What _is_ supported is connecting projects to Git repositories, so that you collaborate across the web app and a Git repository. But this is a fairly recent feature, which definitely did not exist last year.

I didn't even realize this couldn't have been about the issue I was facing because of the timeline :D

> Yes, this is unfortunate. Right now if there are forbidden files, the clone fails. We are working to fix this, so that instead they are just ignored for the purposes of Git sync.

Would it be possible to add slightly more details to the error message (e.g. just noting the specific file type that's not supported) if resolving it will take some more time? Right now it took me quite a bit of experimentation (including many rebases to figure out if it was something in my repo history typst didn't like) to realize the issue was due to a pdf file I had somewhere in the repo.

**Comment by laurmaedje** [comment] 2024-10-10 15:34
> Would it be possible to add slightly more details to the error message (e.g. just noting the specific file type that's not supported) if resolving it will take some more time?

One of our team members is working on the ignore thing as we speak, so it should not take that long.

**Comment by laurmaedje** [comment] 2024-10-11 12:49
Didn't realize how old this issue is when responding ... Anyway, I'll close this. The accepted file thing is tracked better by https://github.com/typst/webapp-issues/issues/447.

**Closed by laurmaedje** 2024-10-11 12:49 UTC
Labels: bug
