### ISSUE TITLE
Can never use file created without `.typ` extension as a main/module file

### ISSUE THREAD

**Issue by Andrew15-5** [typst/webapp-issues#354] opened 2024-05-19 11:01 UTC
### Description

1. Create a project ("a").
2. Create a file without extension ("a").
3. Rename by appending `.typ` ("a.typ").
4. You can't use this as a main/root/module file.

Also, I was porting a local project and created a file with only its base name. After that, I inserted its content and added `.typ`. As a result, I got "Not a typst source file" in the main file where that module is imported.

<details><summary>screenshots</summary>

#325

![image](https://github.com/typst/webapp-issues/assets/37143421/912b660a-a0d1-410e-9369-4599392a4e86)

![image](https://github.com/typst/webapp-issues/assets/37143421/f315f931-ee73-494f-8b4b-6d61defca2ca)

![image](https://github.com/typst/webapp-issues/assets/37143421/1b15f6f1-92f9-44d1-948e-d8535a48a34e)

</details>

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment] 2024-05-19 11:42
Duplicate of https://github.com/typst/webapp-issues/issues/163

**Closed by laurmaedje** 2024-05-19 11:42 UTC
Labels: bug
