### ISSUE TITLE
Setting for Spaces per Indentation Level

### ISSUE THREAD

**Issue by stellarpower** [typst/webapp-issues#171] opened 2023-10-14 16:29 UTC
### Description

Maybe there's an option, but am right in the middle of writing right now and don't see it - I'd like to set the default indentation settings.

It seems Typst defaults to two spaces per tab. Would be good to have an entry in the settings cog menu to configure whether to use tabs or spaces, and how many spaces per tab / indentation level.

Thanks!

### Use Case

Standard UX.

**Comment by chardskarth** [comment] 2024-08-06 04:18
Is there a way to do this? 🙏

One workaround is adding box for each level and setting insets, but given that pagebreak are not allowed within containers, it's not really gonna work.

**Comment by laurmaedje** [comment] 2024-08-06 06:27
@chardskarth are you sure you want the same thing as the author of this issue? The issue is about the number of spaces per tab in the source panel and not at all related to the document layout.

**Comment by chardskarth** [comment] 2024-08-07 04:37
My bad. I think my concern is more related to this one.
 
https://github.com/typst/typst/issues/1278

I edit typst file in neovim. Thanks @laurmaedje

**Comment by laurmaedje** [comment] 2024-11-30 12:44
Closing in favor of https://github.com/typst/webapp-issues/issues/348 which has a bit more details.

**Closed by laurmaedje** 2024-11-30 12:44 UTC
Labels: feature request, editor
