### ISSUE TITLE
Backspace sometimes stops working

### ISSUE THREAD

**Issue by PgBiel** [typst/webapp-issues#230] opened 2023-12-06 22:29 UTC
### Description

Don't have a reliable way to reproduce yet, but basically the preview updates as if the characters were deleted, but the characters stay there in the editor (and are "brought back to life" in the preview when anything other than backspace is inserted).

The problem ceases when a syntax error occurs (backspace begins working normally again).

This had never happened to me until today (using Typst v0.10.0). I only faced the problem once so far, and recorded it below; please see the video for a demonstration.

https://github.com/typst/webapp-issues/assets/9021226/33468000-c358-4965-97fb-2260085e9753

### Reproduction URL

None (can't reproduce reliably yet)

### Browsers

Firefox

### OS

Linux

**Comment by dvdvgt** [comment] 2023-12-10 13:03
I found this to be reproducible with the following input in the web-app:

```
$
1^1
$
```

entered like this "1^space1". Afterwards, at least for me, pressing the arrow keys or backspace has no effect on the editor nor the preview.

**Comment by laurmaedje** [comment] 2023-12-10 13:30
@dvdvgt Thanks for that, I can reproduce it!

**Comment by linuxrider** [comment] 2023-12-15 15:11
This might be related. German keyboard layout with accents. To get the exponent sign `^` the button needs to be pressed twice.
[Bildschirmaufzeichnung vom 2023-12-15, 15-56-04.webm](https://github.com/typst/webapp-issues/assets/5882359/d5e18b69-13b4-402e-9f6e-ab2971f547ef)

**Comment by laurmaedje** [comment] 2023-12-15 21:13
I think I found the reason for the problem in the video now. We're using the CodeMirror editor and had recently updated it to the latest version. However, I just read the more recent changelog and it turns out that this version had a bug that sounds exactly like what's occurring lately:

> Fix a bug that corrupts the editor's internal view tree data structure on some types of edits, putting the editor in a broken state.

I have now updated the app to the newest patched CodeMirror version (currently deploying), which will hopefully resolve the issue. The dead key issue with the circumflex-backspace is unrelated as far as I can tell (since I can reproduce it on different CodeMirror versions and it also happened in Typst since a long time, not only recently.) I have opened an upstream issue for this problem: https://github.com/codemirror/dev/issues/1310

**Comment by laurmaedje** [comment] 2023-12-19 10:19
> I found this to be reproducible with the following input in the web-app:
> ```
> $
> 1^1
> $
> ```
> which I entered like this "1^space1". Afterwards, at least for me, pressing the left arrow key or backspace has no effect on the editor nor the preview.

The [upstream issue](https://github.com/codemirror/dev/issues/1310) has been fixed and I can confirm that that fixes this bug. Now, we just need to wait for a release and bump it.

**Comment by dvdvgt** [comment] 2023-12-19 11:32
> > I found this to be reproducible with the following input in the web-app:
> 
> > ```
> 
> > $
> 
> > 1^1
> 
> > $
> 
> > ```
> 
> > which I entered like this "1^space1". Afterwards, at least for me, pressing the left arrow key or backspace has no effect on the editor nor the preview.
> 
> 
> 
> The [upstream issue](https://github.com/codemirror/dev/issues/1310) has been fixed and I can confirm that that fixes this bug. Now, we just need to wait for a release and bump it.

Nice, thanks for your efforts!

**Comment by laurmaedje** [comment] 2023-12-19 11:50
Actually, we've decided to add a temporary patch to our codebase until there's a release and it's already deployed, so I'm gonna go ahead and close this.

**Closed by laurmaedje** 2023-12-19 11:50 UTC
Labels: bug
