### ISSUE TITLE
Cannot search for module in documentation

### ISSUE THREAD

**Issue by MDLC01** [typst/webapp-issues#353] opened 2024-05-17 13:13 UTC
### Description

Searching for "sys" or "system" in the documentation does not suggest [the System page](https://typst.app/docs/reference/foundations/sys). Similarly, searching for "calc" or "calcultion" does not suggest [the Calculation page](https://typst.app/docs/reference/foundations/calc).

### Reproduction URL

https://typst.app/docs

**Comment by Andrew15-5** [comment] 2024-10-05 12:43
I think this is a duplicate of https://github.com/typst/typst/issues/8271.

**Closed** 2024-11-11 12:58 UTC
Labels: bug, duplicate
