### ISSUE TITLE
Scroll on type on a heading makes the preview jump to the table of contents

### ISSUE THREAD

**Issue by ziiirozone** [typst/webapp-issues#273] opened 2024-02-06 19:44 UTC
### Description

Hello !
If you have a document with a table of contents created with the outline function and you modify the heading in the document, it will make the preview jump to where the heading is in the table of contents instead of showing you where it actually is.

If you create a typst doc with

#outline()
#pagebreak()
= Title
#pagebreak();
hello

and you go to the page with "hello" written in the preview then you change the heading in the .typ doc it will do it.

I believe it should show you the actual heading instead of the table of contents.

I have been loving to write pdf with typst, thanks everyone for your work !

**Comment by laurmaedje** [comment] 2024-02-07 12:19
Duplicate of https://github.com/typst/webapp-issues/issues/87

**Closed by laurmaedje** 2024-02-07 12:19 UTC
Labels: bug
