### ISSUE TITLE
PDF jumping to where others are editing

### ISSUE THREAD

**Issue by christofergartner** [typst/webapp-issues#362] opened 2024-05-28 20:14 UTC
### Description

Often when trying to read the PDF, another person writing in the file will cause the PDF to jump, making it really annoying to read.

Maybe the PDF shouldn't even jump when the user themselves edit somewhere else, or there is an option to "lock" scrolling from typing.

Unsure if it is a Safari problem, or a web app problem unfortunately :/

### Browsers

Safari

### OS

macOS

**Comment by laurmaedje** [comment] 2024-05-28 20:21
Duplicate of #98

**Closed by laurmaedje** 2024-05-28 20:21 UTC
Labels: bug
