### ISSUE TITLE
Changing file extension to `typ` and expecting preview button to appear

### ISSUE THREAD

**Issue by ramithuh** [typst/webapp-issues#220] opened 2023-11-29 05:12 UTC
### Description

If I create a file with an extension other than `.typ` then it is no longer considered to preview even if I change it later to `.typ`.

On the other hand, if I make a `.typ` file and change to something like `.md` it still is able to preview.

### Browsers

Chrome

### OS

macOS

**Comment by laurmaedje** [comment] 2023-11-29 07:38
Duplicate of https://github.com/typst/webapp-issues/issues/163

**Closed by laurmaedje** 2023-11-29 07:38 UTC
Labels: bug
