### ISSUE TITLE
Double page view

### ISSUE THREAD

**Issue by tingerrr** [typst/webapp-issues#466] opened 2024-10-19 10:19 UTC
### Description

The preview could add a mode in which two pages are shown instead of one (possibly by extending to fit the pages). Such a mode should ideally be aware of the text and binding direction and know that for ltr documents, the odd pages are usually on the right.

Here's a zoomed-out example of Okular doing this:
![image](https://github.com/user-attachments/assets/32052289-a353-4b12-802b-216ad76a8c85)

Note that it also supports displaying the facing pages without the first page being centered, this means that odd pages are on the _right_ in this mode.

### Use Case

When writing documents which are intended for print, viewing them as they will be read could help with plenty of things. It also avoids the jarring effect of the inside-outisde margins changing on every odd-even page when scrolling through.

For me personally, I thought of this when constructing specific cases of sections and chapters starting on page boundaries of even and odd pages while writing docs for hydra. Hydra supports enabling a book mode which incorporates knowledge of the binding direction and page count to avoid showing redundant headers when chapters are still visible on the previous open page while reading. Trying to remember the page I was on inside the web app made this way too hard for me.

**Comment by Enivex** [comment] 2024-10-19 11:10
Duplicate of https://github.com/typst/webapp-issues/issues/368

Though this one is way more detailed

**Closed as not planned** 2024-10-19 11:11 UTC
Labels: duplicate, feature request

**Comment by jamesrswift** [comment] 2024-10-19 11:13
@tingerrr its true that your issue is better written - would you be ok if I copy pasted some of what you wrote into #368?

**Comment by tingerrr** [comment] 2024-10-19 11:34
I tried looking for various terms, but didn't find your issue, otherwise I would've simply added a comment there. Sure thing, go ahead, ~~but won't this be the same issue then?~~

Github didn't show the closed message for me, go ahead. :)

**Comment by jamesrswift** [comment] 2024-10-19 11:37
Tbh I thought it might be a duplicate, and myself searched and couldn't even find my own issue!
